//
//  CubeViewModel.swift
//  CubeSolver
//
//  Created by GitHub Copilot
//

import Foundation
import SwiftUI

/// ViewModel managing the state and operations of the Rubik's Cube
/// Conforms to ObservableObject to enable SwiftUI data binding
class CubeViewModel: ObservableObject {
    /// The current state of the Rubik's Cube
    @Published var cube: RubiksCube
    
    /// Array of solution steps generated by the solver
    @Published var solutionSteps: [String] = []
    
    /// Initializes the view model with a solved cube
    init() {
        self.cube = RubiksCube()
    }
    
    /// Scrambles the cube with a random sequence of moves
    /// - Note: Clears any existing solution steps
    func scramble() {
        let scrambleSequence = CubeSolver.scramble(moves: 20)
        CubeSolver.applyScramble(cube: &cube, scramble: scrambleSequence)
        solutionSteps = []
        objectWillChange.send()
    }
    
    /// Solves the current cube configuration and generates solution steps
    /// - Note: Updates the solutionSteps array with the solving algorithm's moves
    func solve() {
        solutionSteps = CubeSolver.solve(cube: &cube)
        objectWillChange.send()
    }
    
    /// Resets the cube to its solved state and clears solution steps
    func reset() {
        cube = RubiksCube()
        solutionSteps = []
        objectWillChange.send()
    }
}
