# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: 70...100
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
        if_ci_failed: error
    
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_ci_failed: error

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true

ignore:
  - "Tests/**"
  - "**/*Tests.swift"
  - "CubeSolver.xcodeproj/**"
  - ".github/**"
  - "docs/**"
  - "**/*.md"

flags:
  unittests:
    paths:
      - Sources/
    carryforward: true
